CREATE TABLE IF NOT EXISTS courses
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name        VARCHAR                                 NOT NULL,
    description VARCHAR                                 NOT NULL,
    field       VARCHAR                                 NOT NULL,
    complexity  INTEGER                                 NOT NULL,
    duration    INTEGER                                 NOT NULL,
    CONSTRAINT pk_courses PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS modules
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name            VARCHAR                                 NOT NULL,
    description     VARCHAR                                 NOT NULL,
    place_in_course INTEGER                                 NOT NULL,
    course_id       BIGINT                                  NOT NULL references courses (id),
    CONSTRAINT pk_modules PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS tasks
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR                                 NOT NULL,
    body      VARCHAR                                 NOT NULL,
    url       VARCHAR                                 NOT NULL,
    module_id BIGINT                                  NOT NULL references modules (id),
    CONSTRAINT pk_tasks PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS files
(
    id           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name         VARCHAR                                 NOT NULL,
    content      BLOB                                    NOT NULL,
    content_type VARCHAR                                 NOT NULL,
    url          VARCHAR                                 NOT NULL,
    module_id    BIGINT                                  NOT NULL references modules (id),
    CONSTRAINT pk_files PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS literature
(
    id        BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name      VARCHAR                                 NOT NULL,
    author    VARCHAR                                 NOT NULL,
    url       VARCHAR                                 NOT NULL,
    module_id BIGINT                                  NOT NULL references modules (id),
    CONSTRAINT pk_literature PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users
(
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name                 VARCHAR                                 NOT NULL,
    age                  INTEGER,
    email                VARCHAR                                 NOT NULL UNIQUE,
    pass                 VARCHAR                                 NOT NULL,
    description          VARCHAR,
    date_time_registered DATETIME                                NOT NULL,
    role                 VARCHAR                                 NOT NULL,
    CONSTRAINT pk_users PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teachers
(
    id      BIGINT NOT NULL,
    user_id BIGINT NOT NULL references users (id),
    CONSTRAINT pk_teachers PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS students
(
    id      BIGINT NOT NULL,
    rating  DOUBLE NOT NULL,
    user_id BIGINT NOT NULL references users (id),
    CONSTRAINT pk_students PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS teachers_courses
(
    teacher_id BIGINT NOT NULL references teachers (id),
    course_id  BIGINT NOT NULL references courses (id),
    CONSTRAINT pk_teachers_courses PRIMARY KEY (teacher_id, course_id)
);

CREATE TABLE IF NOT EXISTS students_courses
(
    student_id     BIGINT  NOT NULL references students (id),
    course_id      BIGINT  NOT NULL references courses (id),
    rating         DOUBLE,
    start_date     DATETIME,
    end_date       DATETIME,
    current_module INTEGER,
    course_status  VARCHAR NOT NULL,
    CONSTRAINT pk_students_courses PRIMARY KEY (student_id, course_id)
);

CREATE TABLE IF NOT EXISTS roles
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    INTEGER                                 NOT NULL,
    user_id BIGINT                                  NOT NULL references users (id),
    CONSTRAINT pk_roles PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS privileges
(
    id      BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name    INTEGER                                 NOT NULL,
    role_id BIGINT                                  NOT NULL references roles (id),
    CONSTRAINT pk_privileges PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS messages
(
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    body           VARCHAR                                 NOT NULL,
    date_time_sent DATETIME                                NOT NULL,
    from_id        BIGINT                                  NOT NULL references users (id),
    tu_id          BIGINT                                  NOT NULL references users (id),
    CONSTRAINT pk_messages PRIMARY KEY (id)
);